---
apiVersion: v1
kind: Service
metadata:
  name: dubbo-spring-provider-svc
  labels:
    app: dubbo-sring-provider-svc
spec:
  ports:
  - port: 12345
    name: server
  type: NodePort
  selector:
    app: dubbo-spring-provider
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dubbo-spring-provider
spec:
  replicas: 1
  selector:
   matchLabels:
    app: dubbo-spring-provider
  template:
    metadata:
      labels:
        app: dubbo-spring-provider
    spec:
      nodeSelector:
        zk: zk-2
      containers:
      - name: dubbo-admin-backend
        imagePullPolicy: Always
        image: dockeryanxiao/dubbo-spring-boot-provider-demo:0.0.1
        ports:
        - containerPort: 12345
        env:
        - name: dubbo.registry.address
          value: zookeeper://zk-2-svc:2181
